language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

# lock distro so new future defaults will not break the build
dist: trusty

matrix:
  allow_failures:
    - php: 5.4
    - php: 7.1
    - php: nightly

install:
  - ./travis-init.sh
  - composer config platform.php $(php -r 'echo PHP_VERSION;')
  - composer install -n

script:
  - ./vendor/bin/phpunit --exclude-group permissions
  - export phploc=~/.phpenv/versions/$(phpenv version-name)/bin/php
  - sudo $phploc ./vendor/bin/phpunit --group permissions
