language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - ./travis-init.sh
  - composer install -n

script:
  - ./vendor/bin/phpunit --exclude-group permissions
  - export phploc=~/.phpenv/versions/$(phpenv version-name)/bin/php
  - sudo $phploc ./vendor/bin/phpunit --group permissions
