language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  include:
    - name: "Windows"
      os: windows
      language: shell # no built-in php support
      before_install:
        - choco install php
        - choco install composer
        - export PATH="$(powershell -Command '("Process", "Machine" | % { [Environment]::GetEnvironmentVariable("PATH", $_) -Split ";" -Replace "\\$", "" } | Select -Unique | % { cygpath $_ }) -Join ":"')"
      install:
        - composer install -n

  allow_failures:
    - php: 5.4
    - php: 7.1
    - php: nightly
    - os: windows

install:
  - ./travis-init.sh
  - composer install -n

script:
  - ./vendor/bin/phpunit --exclude-group permissions
  - export phploc=~/.phpenv/versions/$(phpenv version-name)/bin/php
  - sudo $phploc ./vendor/bin/phpunit --group permissions
