#!/usr/bin/env php
<?php

use React\EventLoop\Factory as LoopFactory;
use React\Filesystem\ChildProcess\Process;
use WyriHaximus\React\ChildProcess\Messenger\Factory as MessengerFactory;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

$loop = LoopFactory::create();

/**
 * Setup communication with the parent adapter
 */
$recipient = MessengerFactory::child($loop);

/**
 * Hook IO execution handler up with the parent adapter communication
 */
$process = new Process($recipient);

$loop->run();
