name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }} with ${{ matrix.extensions }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        php:
          - "8.2"
          - "8.1"
          - "8.0"
          - "7.4"
        extensions:
          - ""
          - "uv-amphp/ext-uv@master"
          - "uv-amphp/ext-uv@master, eio"
          - "eio"
    steps:
      - uses: actions/checkout@v2
      - name: Install libuv
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libuv1-dev
      - name: Install ext-eio
        if: matrix.os == 'ubuntu-latest' && (matrix.extensions == 'eio' || matrix.extensions == 'uv-amphp/ext-uv@master, eio')
        run: sudo pecl install eio || sudo pecl install eio-beta
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: ${{ matrix.extensions }}
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text --debug
  PHPUnit-Docker:
    name: PHPUnit (PHP ${{ matrix.php }} on Docker)
    runs-on: ubuntu-latest
    container:
      image: wyrihaximusnet/php:${{ matrix.php }}-nts-alpine-slim-dev-root
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1"
          - "8.0"
          - "7.4"
    steps:
      - uses: actions/checkout@v2
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
